debug = false

# Define logging level
logLevel = "INFO"
# Define entry points.
defaultEntryPoints = ["https", "http"]

# Configure the entry points.
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  compress = true
  [entryPoints.https.tls]

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "[domain_name_here]"
watch = true
exposedbydefault = false

[acme]
email = "[your_email_here]"
storage = "acme.json"
entryPoint = "https"
OnHostRule = true
[acme.httpChallenge]
entryPoint = "http"